### ISSUE TITLE
How to access the dataset

### ISSUE THREAD

**Issue by ArshaNagrani** [juliasilge/women-in-film#2]
Hi, 

Have you released the dataset of scripts that you used to the public? If so, where can I access them?

**Comment by juliasilge** [comment]
Unfortunately, the scripts can't be made public in their entirety because they are not in the public domain, they are the IP of various people, etc. The work created **from** the scripts (i.e. [what you see here](https://pudding.cool/2017/08/screen-direction/)) can be made public because it involves new work we did, but we can't share the scripts themselves because we don't own the rights to them.
